### ISSUE TITLE
Application breaking when Zf\Hal is not 1.4

### ISSUE THREAD

**Issue by vincequeiroz** [zfcampus/zf-content-negotiation#74]
This module uses the getEntity method, but this method only exists in version 1.4.

https://github.com/zfcampus/zf-content-negotiation/blob/1.2.1/src/JsonModel.php#L82
https://github.com/zfcampus/zf-hal/blob/1.4.0/src/Entity.php#L84
https://github.com/zfcampus/zf-hal/blob/1.3.1/src/Entity.php

I believe it should be required not require-dev
https://github.com/zfcampus/zf-content-negotiation/blob/master/composer.json#L44

**Comment by weierophinney** [comment]
> This module uses the getEntity method, but this method only exists in version 1.4

Prior to the 1.2.0 release of this component, *it was using property overloading* vs the method itself. We *still had zf-hal listed as a dev dependency*. This was because the `JsonModel` would work without the zf-hal classes being present; essentially, those checks would fail, and it would fall through to either generating a JSON-P callback or a JSON payload.

My point is: your diagnosis is incorrect. What we need to do is check to see if the method exists and use it if present, and fallback to the property access if it doesn't; that allows usage with earlier versions of zf-hal.

I'll get a pull request with that ready shortly.
