### ISSUE TITLE
Incompatible changes in RequestFactory 

### ISSUE THREAD

**Issue by merkushin** [zfcampus/zf-content-negotiation#98]
In [zf-content-negotiation 1.3.1](https://github.com/zfcampus/zf-content-negotiation/commit/439460235671568c5b4320653b52b85edddfea37) we got change of one line.

Original:
```
if (Console::isConsole()) {
```

Changed:
```
if (PHP_SAPI === 'cli') {
```
Commit message:
```
Make zend-console a suggested dependency required for console requests only
```

Here are two problems with this change.

* In case of console application it will fail if you will not use \Zend\Console. And IMO it is not obvious. Strong dependency become hidden, but Console is still required.
* This change of _patch_ version has incompatible changes. (From my experience: In our functional test we set $isConsole to false and expect to get HttpRequest, but get CosoleRequest.)

**Comment by weierophinney** [comment]
In your first bullet point, the code _would have failed prior to the 1.3.1 release as well_, because zend-console has never been a direct requirement of the package. #86 finally adds it as a _suggestion_ to the `composer.json`, which is an improvement.

As to your second bullet point, am I to understand that the new failure is in a _functional_ or E2E test? If so, what are you using for your tests, exactly? Depending on what you are using, we may be able to provide a workaround. However, the point of that factory _is to vary which request type to return based on the SAPI_, and the new mechanism is certainly valid, and _prevents a production dependency issue_ reported by users. We will not revert the code in order to fix a _testing_ issue.

As such, the workaround we provide will be specific for your application, and not something we push back into the component. But I'm sure we can provide you with something. I just need answers to the above questions.

**Comment by basselin** [comment]
In my case, `AbstractControllerTestCase` failed with this error :

**Error: Call to undefined method Zend\Console\Request::getQuery()**

If I overwrite the `ZF\ContentNegotiation\Factory\RequestFactory` with the method `Console::isConsole()`

Every test works fine.

**Comment by merkushin** [comment]
@weierophinney Thank you for your response.

Sorry, I didn't mention two things:
1. We use \Zend\Console, so the usage of this component itself is not a problem for _us_. The problem is that we expect HttpRequest (after setting $isConsole = false), but still getting ConsoleRequest. And this is backward compatibility issue, that should cause change of major version (in case you use semantic versioning), not patch version.
2. We fixed this problem for our test. Description below.

> As to your second bullet point, am I to understand that the new failure is in a functional or E2E test? If so, what are you using for your tests, exactly? Depending on what you are using, we may be able to provide a workaround. 

We test our Apigility project with PHPUnit 6.4.4. 
Our hot-fix is to configure service manager with config passed to application bootstrap.
Something like this:

```
$bootstrap = new Bootstrap(['app_name' => 'TestApi']);
$applicationConfig = $this->applicationConfig;

// https://github.com/zfcampus/zf-content-negotiation/blob/1.3.1/src/Factory/RequestFactory.php
// Changes in this release lead to creation of Console Request in our tests
if (!isset($applicationConfig['service_manager']['services']['Request'])) {
    $applicationConfig['service_manager']['services']['Request'] = new \Zend\Http\PhpEnvironment\Request();
}

$this->application = $bootstrap->bootstrapApi($applicationConfig);
```

This is not the smartest solution, but as temporary it is ok.
